# Generated by Django 5.2.5 on 2025-10-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy_data', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('meter_disconnected', 'Compteur déconnecté'), ('pv_cutting', 'Écrêtage PV'), ('battery_fault', 'Anomalie batterie'), ('low_production', 'Production PV anormalement basse'), ('overload', 'Surcharge réseau')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.IntegerField(default=1)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy_data.energyreading')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='sites.site')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
