# Generated by Django 5.2.5 on 2025-10-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('total_load_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('genset_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('pv_production_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('battery_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('pv_theoretical_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sites.site')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['site', '-timestamp'], name='energy_data_site_id_092d1f_idx')],
                'unique_together': {('site', 'timestamp')},
            },
        ),
    ]
