# Generated by Django 4.2.7 on 2025-07-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Lynkevo Admin', max_length=255)),
                ('site_description', models.TextField(blank=True, default='Dashboard administratif pour Lynkevo')),
                ('contact_email', models.EmailField(default='admin@lynkevo.com', max_length=254)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=100)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=False)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=30)),
                ('password_expiry', models.IntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
