# Generated by Django 5.2.5 on 2025-08-28 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_sitesettings_bio_sitesettings_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='last_name',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
