# Generated by Django 5.2.5 on 2025-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('technicien', 'Technicien'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
