# Generated by Django 5.2.5 on 2025-10-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topology', models.CharField(choices=[('solar_battery', 'Panneau solaire + Batterie'), ('solar_se_battery', 'Panneau solaire + SE + Batterie'), ('solar_generator', 'Panneau solaire + Groupe électrogène'), ('jirama', 'Jirama (ou fournisseur national)')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
    ]
